project_id = "zdvppjgxjyqqwrekougp"

[functions.fetch-vehicle-details]
verify_jwt = false

[functions.send-transfer-notification]
verify_jwt = false

[functions.check-expiry-alerts]
verify_jwt = false

[functions.analyze-document]
verify_jwt = false

[functions.verify-vehicle]
verify_jwt = false

[functions.admin-data]
verify_jwt = false

[functions.send-ownership-claim-notification]
verify_jwt = false
